### ISSUE TITLE
users

### ISSUE THREAD

**Issue by csotomon** [Primechain/yobiapps#1]
Hi, where are the usernames and password saved?

**Comment by csotomon** [comment]
checking the code, the username and password is saved in the blockchain with streams.

Why did you choose this option? there is no way to the user modify the password or the account details.

**Comment by geekongit** [comment]
As you may not be able to change the existing data in the blockchain but if you want to bring in a password/account details update feature then you can push a new item to the stream which will contain the updated password/account details for the user. You can always fetch the most recent item in the stream with the user name as the key.
