### ISSUE TITLE
Prime Vault Download not working

### ISSUE THREAD

**Issue by girish8050517990** [Primechain/yobiapps#2]
Pasting the transaction ID and clicking on view doesn't do anything.

**Comment by geekongit** [comment]
The issue has been fixed. Before pulling the latest code backup RPC_PORT, RPC_USER, RPC_PASSWORD values from config.php. After pulling the latest, replace RPC_PORT, RPC_USER, RPC_PASSWORD in config.php with the backed up vaules. It should work fine.

**Comment by 9611838416m** [comment]
Prime vault upload stopped working now. Files are uploaded to the server but no new item is created in the streams. Hence no transaction ID is not shown.

**Comment by longsyee** [comment]
im having same issue some file not supported and some are unable to download white page

**Comment by geekongit** [comment]
The issue is resolved. Please backup your config.php and pull the latest code.
